/* Generated by _import-photos.ps1 -- re-run it after adding photos to Drive.
   You CAN safely edit the caption text below; it is preserved on re-import.
   Photos appear on the page in the order listed here. */
window.GALLERY_PHOTOS = [
  { src: "photos/10c69e11-84a5-45ff-936b-188f5c30ec56.jpg", caption: "" },
  { src: "photos/1c016f18-7dce-4f24-8658-d0874659a504.jpg", caption: "" },
  { src: "photos/1ce95998-a775-4d6c-b9c3-df6a2f946bf1.jpg", caption: "" },
  { src: "photos/2f065842-fae6-4641-84ee-bad0be37392a.jpg", caption: "" },
  { src: "photos/60e2cfb5-3836-473a-a371-1921a4be01b3.jpg", caption: "" },
  { src: "photos/68b0710f-3abe-4059-a771-412b307c1ac4.jpg", caption: "" },
  { src: "photos/a3842ac9-d971-42cf-8b13-1d741e61d52f.jpg", caption: "" },
  { src: "photos/a5730e71-19c4-4397-b311-2c8d32f81608.jpg", caption: "" },
  { src: "photos/dfb8824c-6716-4d78-a833-c15bd3ab2345.jpg", caption: "" },
  { src: "photos/img-5604.jpg", caption: "" },
  { src: "photos/img-5662.jpg", caption: "" },
  { src: "photos/img-5948.jpg", caption: "" },
  { src: "photos/img-6025.jpg", caption: "" },
];
